### ISSUE TITLE
Report not showing

### ISSUE THREAD

**Issue by CoteDave** [maximtrp/tmplot#1]
Hi, 

I tried the code example but nothing happens when running:

tmp.report(model, docs=docs, width=250)

Is it only Working inside a jupyter notebooks?

If yes, is There a way to export the chart as .html?

Finally, is it possible to plot the chart inside a streamlit application ?

Thanks!

**Comment by maximtrp** [comment]
Hello! Report interface is supported only in Jupyter Notebooks now. The option to export the report to a HTML file may be added in a future release. `tmplot` is based on `Altair` package, therefore it is probably possible to use the plots in a `streamlit` application. I need some time to explore it as I have never used it before.

**Comment by CoteDave** [comment]
Thanks you for the fast answer!

Make sens now! Html standalone would be a very Nice addon (to share the dashboard with business users)

Altair charts are supported in streamlit, i'll try it and let you know if it Works !

Thanks !

**Comment by CoteDave** [comment]
Finally, the output of tmplot.report() is a VBox object (Seems to be a mix of ipywidgets and Altair Chart). So, I did not find a way to plot it in Streamlit (I tried the altair_chart() and FigureWidget() components).

Thanks!

**Comment by maximtrp** [comment]
You can try to use [visualization functions](https://tmplot.readthedocs.io/en/latest/tmplot_vis.html) (it's indeed a VBox object containing all the stuff).
