### ISSUE TITLE
Problem when analyzing the model.

### ISSUE THREAD

**Issue by AStogov** [maximtrp/tmplot#5]
When I used tmplot to visualize my bitermplus model, It worked but **Topics scatter plot** didn't show and I got this **warning**:
```
E:\Python\lib\site-packages\tmplot\_helpers.py:38: UserWarning: Please install "f{package_name}" package to analyze its models.
Run `pip install f{package_name}` in the console.
```
However, I've never missed any package and requirement. Definitely I've already installed bitermplus. Relevant words (terms) and Top documents in a topic worked well.
And as well I got a JS error. I know little about JS code.
```
Javascript Error: Cannot read property 'forEach' of undefined
This usually means there's a typo in your chart specification. See the javascript console for the full traceback.
```
Here is my code:

```python
......
import bitermplus as btm
import numpy as np
import pandas as pd
X, vocab, vocab_dict = btm.get_words_freqs(text)
# print(vocab_dict)
tf = np.array(X.sum(axis=0)).ravel()
# print(tf)
docs_vec = btm.get_vectorized_docs(text, vocab)
docs_len = list(map(len, docs_vec))
biterms = btm.get_biterms(docs_vec)
# print(biterms)
model = btm.BTM(X, vocab, seed=12321, T=8, M=20, alpha=50/8, beta=0.01)
model.fit(biterms, iterations=20)
p_zd = model.transform(docs_vec)
import tmplot as tmp
tmp.report(model=model, docs=text)
......
```

**Comment by maximtrp** [comment]
Thank you for reporting! The warning you get is due to absence of tomotopy or gensim (it is OK, it is just a warning). I've noticed a bug in a f-string, I will fix it in the next release.

The main error here is related to Javascript. What version of `altair` are you using?

**Comment by AStogov** [comment]
你好，我正有事不在，如果要了解详情，请访问这里

**Comment by AStogov** [comment]
The version altair is **4.2.0**. Is there any version conflict?

**Comment by maximtrp** [comment]
I have released a fixed version. Try it please

**Comment by AStogov** [comment]
It works fine. Thanks!
