### ISSUE TITLE
valueError: perplexity must be less than n_samples 

### ISSUE THREAD

**Issue by Yif18** [maximtrp/tmplot#9]
My corpus has 49 records, which is not a short text.
No error is reported when T>=6, but an error is reported when T<=5

model = btm.BTM(X, vocab, T=5, M=50, alpha=1, beta=0.01)
model.fit(biterms, iterations=100)

tmp.report(model=model, docs=content_flat)
**valueError: perplexity must be less than n_samples** 

I found that this error is not directly related to the level of perplexity
T=5   perplexity:263.31198210806156
T=6   perplexity:251.15355539215517
the number of records is 49

Name: tmplot
Version: 0.1.0
Name: bitermplus
Version: 0.7.0

This error has caused me a lot of trouble. I look forward to your reply. Thank you.

**Comment by maximtrp** [comment]
Hello! Thank you for reporting this. Will check it as soon as I can.

**Comment by maximtrp** [comment]
New version is out! Please check it

**Comment by Yif18** [comment]
> New version is out! Please check it
I have tried version 0.1.1 and the problem has been solved. Thank you very much.

**Comment by Yif18** [comment]
I have tried version 0.1.1 and the problem has been solved. Thank you very much.
